site_name: PowerAlto4 Docs
theme: readthedocs
pages:
  - Home: index.md
  - Cmdlets:
    - Invoke-PaApiReport: cmdlets/Invoke-PaApiReport.md
    - Invoke-PaCustomReport: cmdlets/Invoke-PaCustomReport.md
    - Get-PaDevice: cmdlets/Get-PaDevice.md
    - Invoke-PaApiConfig: cmdlets/Invoke-PaApiConfig.md
