site_name: PowerAlto4 Docs
theme: readthedocs
pages:
  - Home: index.md
  - Cmdlets:
    - Get-PaDevice: cmdlets/Get-PaDevice.md
    - Invoke-PaApiOperation: cmdlets/Invoke-PaApiOperation.md
    - Set-PaCustomReport: cmdlets/Set-PaCustomReport.md
    - Invoke-PaApiConfig: cmdlets/Invoke-PaApiConfig.md
    - Get-PaConfigDiff: cmdlets/Get-PaConfigDiff.md
    - Get-PaJob: cmdlets/Get-PaJob.md
    - Invoke-PaApiReport: cmdlets/Invoke-PaApiReport.md
    - Get-PaCustomReport: cmdlets/Get-PaCustomReport.md
    - Invoke-PaCustomReport: cmdlets/Invoke-PaCustomReport.md
    - Invoke-PaCommit: cmdlets/Invoke-PaCommit.md
